services:
  app:
    build:
      context: .
      target: development
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start -- --host 0.0.0.0 --poll 2000

  app-main:
    build:
      context: .
      target: production
    ports:
      - '8080:80'
    profiles:
      - main
