# Identificacao do projeto
sonar.projectKey=danielsaviosec_desafio-attus
sonar.organization=danielsaviosec
sonar.host.url=https://sonarcloud.io
sonar.projectName=desafio-attus
sonar.projectVersion=1.0

# Codigo fonte e testes
sonar.sources=src,exercises
sonar.tests=src,exercises
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/coverage/**,**/.angular/**

# Cobertura de testes (Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# TypeScript/Angular
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
